### ISSUE TITLE
Question: Is this intended to spawn a docker container when connecting through SSH?

### ISSUE THREAD

**Issue by vnijs** [yuvipanda/jupyterhub-ssh#12]
If so, that would be *really* nice.

**Comment by yuvipanda** [comment]
Heya! Thanks for your interest :D 

It talks to JupyterHub only, so it doesn't know what is going to be spawned. So if your JupyterHub is configured to use [dockerspawner](https://github.com/jupyterhub/dockerspawner), it'll spawn a docker container. If your JupyterHub is configured to use [KubeSpawner](https://github.com/jupyterhub/kubespawner), it'll spawn a kubernetes pod (this is how I use it).

Hope that was useful!

**Comment by vnijs** [comment]
Nice! Looking forward to trying this out. I'll need some docs to figure out how to make it work however :)
