### ISSUE TITLE
Helm repo is down

### ISSUE THREAD

**Issue by TomAugspurger** [yuvipanda/jupyterhub-ssh#23]
Hi Yuvi! Thanks for this package, it seems to be working great, and I'll try to roll it out to the pangeo hubs over the next couple weeks.

It looks like the index of charts at https://yuvipanda.github.io/jupyterhub-ssh/ is broken right now. I was able to deploy it by downloading the chart manually.

**Comment by yuvipanda** [comment]
Awesome, @TomAugspurger! 

There's no pretty HTML page there, but it's still a valid repo since https://yuvipanda.github.io/jupyterhub-ssh/index.yaml exists. Maybe that file explicitly needs to be the repo?

**Comment by TomAugspurger** [comment]
Oh thanks. I guess the issue was the no stable release, so when I did `helm repo search` it turned up blank.

**Comment by darose** [comment]
I am also unable to successfully use the helm chart.

	$ helm install --dry-run -n <our_namespace> jupyterhub-ssh/jupyterhub-ssh --set hubUrl=<our url> --set-file hostKey=<our-ssh-key> -g --version 0.0.1-n062.h2759fb4
	Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[0].persistentVolumeClaim): missing required field "claimName" in io.k8s.api.core.v1.PersistentVolumeClaimVolumeSource

Any idea what's wrong / how to fix?

**Comment by consideRatio** [comment]
@darose I opened https://github.com/yuvipanda/jupyterhub-ssh/issues/24. This Helm chart contain two services, SFTP stuff and SSH.

I'm not 100%, but I think they are independent from each other.
