### ISSUE TITLE
Automatically seed the SSH key needed if unspecified

### ISSUE THREAD

**Issue by consideRatio** [yuvipanda/jupyterhub-ssh#38]
http://masterminds.github.io/sprig/crypto.html describes how `sprig`, a library exposing functions that `helm` can use, includes `genPrivateKey` that allows us to generate a private key.

I suggest that like the z2jh helm chat does, this Helm chart generates such private key unless explicitly passed and saves it into a k8s Secret and relies on the `lookup` function to catch it during helm template rendering. In other words, that we seed the SSH key for users that doesn't specify it, and we make sure to reuse a previously seeded SSH key.

For some reference examples on doing this, see:
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1993
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2312
- [Link to code snippet](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/68dd23b01e5b6102fc2fd6e486006528100ade85/jupyterhub/templates/hub/_helpers-passwords.tpl#L16-L47)

**Comment by yuvipanda** [comment]
Wow this would be pretty fucking awesome!
