### ISSUE TITLE
Helm chart jupyterhub-ssh not found in https://yuvipanda.github.io/jupyterhub-ssh/ repository

### ISSUE THREAD

**Issue by MarineChap** [yuvipanda/jupyterhub-ssh#62]
Hello, 

Did the helm chart move to another place ? I have an error when trying to install the helm chart following the Readme documentation. Did I miss an info somewhere ? 

````
helm install jupyterhub-ssh  --repo https://yuvipanda.github.io/jupyterhub-ssh/ jupyterhub-ssh    --set hubUrl=https://jupyter.example.org    --set ssh.enabled=true    --set sftp.enabled=false
```

`Error: chart "jupyterhub-ssh" not found in https://yuvipanda.github.io/jupyterhub-ssh/ repository`

Thanks. Have a good day.

**Comment by MarineChap** [comment]
And of course I found this issue two minutes later : #35  and adding the --version 0.0.1-n142.h402a3d6 works.

(Eventually considere to make the ReadMe a little more explicit about the version would be nice) 

I will close it. Sorry for the noise.

**Comment by consideRatio** [comment]
Thanks for solving this yourself @MarineChap! I agree it would be useful, I consider this issue represented currently by https://github.com/yuvipanda/jupyterhub-ssh/issues/45.
