### ISSUE TITLE
cert error

### ISSUE THREAD

**Issue by zhuzeyu22** [yuvipanda/jupyterhub-ssh#64]
autohttps log 
------------------
time="2021-11-24T14:06:06Z" level=debug msg="legolog: [INFO] [hub.jupyterhub-system.svc.cluster.local] acme: Obtaining bundled SAN certificate"
time="2021-11-24T14:06:07Z" level=error msg="Unable to obtain ACME certificate for domains \"hub.jupyterhub-system.svc.cluster.local\" : unable to generate a certificate for the domains [hub.jupyterhub-system.svc.cluster.local]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"hub.jupyterhub-system.svc.cluster.local\": Domain name does not end with a valid public suffix (TLD)" providerName=default.acme
time="2021-11-24T14:16:03Z" level=warning msg="A new release has been found: 2.5.4. Please consider updating."

**Comment by zhuzeyu22** [comment]
helm install jupyterhub jupyterhub/jupyterhub --namespace jupyterhub-system --create-namespace --values jupyter-hub-values.yaml --version 1.1.4

**Comment by zhuzeyu22** [comment]
I cant use it ,  qwq

**Comment by zhuzeyu22** [comment]
~ $ nslookup hub.jupyterhub-system.svc.cluster.local
Server:         172.19.0.10
Address:        172.19.0.10:53

*** Can't find hub.jupyterhub-system.svc.cluster.local: No answer

Name:   hub.jupyterhub-system.svc.cluster.local
Address: 172.19.190.48

~ $ 
~ $ ps
PID   USER     TIME  COMMAND
    1 nobody    0:00 /tini -- /usr/local/bin/acme-secret-sync.py watch-save --label=app=jupyterhub --label=release=jupyterhub --label=chart=ju
    6 nobody    0:00 python3 /usr/local/bin/acme-secret-sync.py watch-save --label=app=jupyterhub --label=release=jupyterhub --label=chart=jup
   30 nobody    0:00 sh -c clear; (bash || ash || sh)
   36 nobody    0:00 ash
   42 nobody    0:00 ps

**Comment by consideRatio** [comment]
You seem to have tried to use a version that isn't available, you can use version 1.2.0 of the JupyterHub Helm chart.

This is not an issue of this project, but a configuration issue of how you are using the JupyterHub Helm chart. Please see z2jh.jupyter.org for a reference on how to work with that Helm chart, and after that is installed successfully, you can try installing the jupyterhub-ssh Helm chart according to the README.md in this repo.

If you need further help please refer to discourse.jupyter.org, if you become confident there is a bug in this Helm chart or other project, it is relevant to open an issue on GitHub but otherwise please use discourse.jupyter.org. Doing that helps reduce the maintenance burden from the maintainers of this and other open source projects in the jupyter ecosystem.

Best regards
Erik

**Comment by zhuzeyu22** [comment]
![image](https://user-images.githubusercontent.com/13432873/143378210-c9de52a9-ef36-482d-9a3a-ecf5d21164f4.png)

**Comment by zhuzeyu22** [comment]
![image](https://user-images.githubusercontent.com/13432873/143378266-261f0786-61bc-492d-a834-0e4c5fdcb6d3.png)

**Comment by zhuzeyu22** [comment]
1、version 1.1.4 is. error
2、config need have hosts , if  no. hosts , error too

**Comment by zhuzeyu22** [comment]
![image](https://user-images.githubusercontent.com/13432873/143378358-6bdc7b51-573b-43c6-8489-c3ae50e9d3d3.png)

**Comment by zhuzeyu22** [comment]
And now, I update my helm JH version to 1.2.0 (latest) , but still can not work .
We can see the. sam error.
-------------------------------------------------------
time="2021-11-25T04:07:29Z" level=debug msg="legolog: [INFO] [hub.jupyterhub-system.svc.cluster.local] acme: Obtaining bundled SAN certificate"
time="2021-11-25T04:07:29Z" level=error msg="Unable to obtain ACME certificate for domains \"hub.jupyterhub-system.svc.cluster.local\" : unable to generate a certificate for the domains [hub.jupyterhub-system.svc.cluster.local]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"hub.jupyterhub-system.svc.cluster.local\": Domain name does not end with a valid public suffix (TLD)" providerName=default.acme

**Comment by consideRatio** [comment]
Nothing you do will provide you with a cert from letsencrypt (giving you public domain certs) to a non-public domain name, no matter if cert-manager or traefik is used against letsenceypt.

Read about the ACME protocol to learn more, or just take my word for it. Please see documentation, then use discourse.jupyter.org, and be mindful of the time invested by anyone helping you.

**Comment by zhuzeyu22** [comment]
OK ,thank for you time.
