### ISSUE TITLE
helm chart repo  404 error

### ISSUE THREAD

**Issue by zhuzeyu22** [yuvipanda/jupyterhub-ssh#65]
repo https://yuvipanda.github.io/jupyterhub-ssh/   is. 404
I run this command 
----------
helm install jupyterhub-ssh \
   --repo https://yuvipanda.github.io/jupyterhub-ssh/ jupyterhub-ssh \
   --set hubUrl=https://hub/ \
   --set ssh.enabled=true \
   --set sftp.enabled=false \
   --namespace jupyterhub-system
----------
And then I got a error
Error: INSTALLATION FAILED: chart "jupyterhub-ssh" not found in https://yuvipanda.github.io/jupyterhub-ssh/ repository
It is so sadly

**Comment by consideRatio** [comment]
You need to specify a version excplicitly for now, inspect index.yaml from the helm chart repo url for the latest version number.
